const gameBackground = document.querySelector('.game-background')
const hungerStat = document.querySelector('#hunger-val')
const happyStat = document.querySelector('#happy-val')
const energyStat = document.querySelector('#energy-stat')
const dayCount = document.querySelector('#day-val')